// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr7_vps5dI1ZT8R53081NzQ8EVXwxcS58',
    appId: '1:686369155609:web:390d24341449bc38e81888',
    messagingSenderId: '686369155609',
    projectId: 'uppgift3-ab122',
    authDomain: 'uppgift3-ab122.firebaseapp.com',
    storageBucket: 'uppgift3-ab122.firebasestorage.app',
    measurementId: 'G-VFR8NYFBXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZJoHvc5e9jQD-OfweUovNuFSHY-Pjbs8',
    appId: '1:686369155609:android:8323c3e1061e9a3de81888',
    messagingSenderId: '686369155609',
    projectId: 'uppgift3-ab122',
    storageBucket: 'uppgift3-ab122.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVzp8inYZCME6QO9E4NJTamTCuBBmUJlk',
    appId: '1:686369155609:ios:a51643c7e60cccb9e81888',
    messagingSenderId: '686369155609',
    projectId: 'uppgift3-ab122',
    storageBucket: 'uppgift3-ab122.firebasestorage.app',
    iosBundleId: 'com.example.uppgift3NewApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVzp8inYZCME6QO9E4NJTamTCuBBmUJlk',
    appId: '1:686369155609:ios:a51643c7e60cccb9e81888',
    messagingSenderId: '686369155609',
    projectId: 'uppgift3-ab122',
    storageBucket: 'uppgift3-ab122.firebasestorage.app',
    iosBundleId: 'com.example.uppgift3NewApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr7_vps5dI1ZT8R53081NzQ8EVXwxcS58',
    appId: '1:686369155609:web:bdb4b212392e8091e81888',
    messagingSenderId: '686369155609',
    projectId: 'uppgift3-ab122',
    authDomain: 'uppgift3-ab122.firebaseapp.com',
    storageBucket: 'uppgift3-ab122.firebasestorage.app',
    measurementId: 'G-3JQGVG5BD7',
  );
}
